- block:
    - debug: msg="Configuring application {{ item.stack_name }}"
    - name: configure application context
      cloudformation:
        region: "{{ region | default('eu-west-1') }}"
        stack_name: "{{ item.stack_name}}"
        profile: "{{ profile }}"
        template: "build/{{item.application}}.cf.yml"
        template_parameters: "{{ item.template_parameters }}"
        disable_rollback: true
        tags: "{{ aws_tags | to_json }}"

- block:
    - name: get stack facts
      cloudformation_facts:
        profile: "{{ profile }}"
        stack_name: "{{ item.stack_name }}"
        stack_resources: true
      changed_when: false
    - name: set stack facts
      set_fact:
        Stack: "{{ Stack| default({}) | combine({ item.stack_name : cloudformation[item.stack_name] },recursive=True) }}"

    - name: set stack facts in list
      set_fact:
        StackNames: "{{ StackNames | default([]) | list }}"

    - name: set stack facts in list
      set_fact:
        StackNames: "{{ StackNames + [ item.stack_name ]  }}"

    - name: upload s3
      aws_s3:
        region: "{{ region }}"
        profile: "{{ profile }}"
        mode: put
        overwrite: never
        src: "{{ src_code }}"
        bucket: "{{ Stack[item.stack_name]['stack_outputs']['BucketName'] }}"
        object: "{{ src_code }}"
      when: item.application == 's3'

    - name: delete source code
      file: path="{{ src_code }}" state=absent
      when:
        - item.application == 's3'
        - not debug | bool

    - name: Stack.Facts variable
      debug: msg={{ Stack }}
      when: debug | bool

    - name: StackNames.Facts variable
      debug: msg={{ StackNames }}
      when: debug | bool