---
# tasks file for aws-lambda
  - name: Create build folder if does not exists
    file:
        path: "build"
        state: directory

  - name: configure cloud formation stacks
    template: src={{role_path}}/templates/cloud_formation/{{item}}.cf.yml
        dest=build/{{item}}.cf.yml
    with_items:
      - s3
      - lambda
      - gateway

  - name: provison resources
    include_tasks: cloud_formation.yml
    with_items:
      - application: s3
        stack_name: "{{ aws_lambda.s3.stack_name }}"
        template_parameters: {}
      - application: lambda
        stack_name: "{{ aws_lambda.lambda.stack_name }}"
        template_parameters: "{{ aws_lambda.lambda.template_parameters }}"
      - application: gateway
        stack_name: "{{ aws_lambda.gateway.stack_name }}"
        template_parameters: "{{ aws_lambda.gateway.template_parameters }}"
