---
# tasks file for aws-lambda
  - name: Create build folder if does not exists
    file:
        path: "build"
        state: directory

  - name: set lambda version stack
    set_fact:
        lambda_version_stack_name: "{{ aws_lambda.lambda.stack_name }}-version-{{ app_version }}"
  - name: set gateway stage stack
    set_fact:
        gateway_stage_stack_name: "{{ aws_lambda.gateway.stack_name }}-{{ env }}"

  - block:
      - name: configure s3 and lambda stack
        include_tasks: configure_cloud_formation_stack.yml
        with_items:
            - s3
            - lambda
            - lambda-version
      - name: provison s3 and lambda
        include_tasks: cloud_formation.yml
        with_items:
          - application: s3
            stack_name: "{{ aws_lambda.s3.stack_name }}"
            template_parameters: {}
          - application: lambda
            stack_name: "{{ aws_lambda.lambda.stack_name }}"
            template_parameters: "{{ aws_lambda.lambda.template_parameters }}"
          - application: lambda-version
            stack_name: "{{lambda_version_stack_name}}"
            template_parameters:
                Version: "{{ app_version }}"
                LambdaStack: "{{ aws_lambda.lambda.stack_name }}"
  - block:
    - name: configure gateway stacks
      include_tasks: configure_cloud_formation_stack.yml
      with_items:
            - gateway
            - gateway-stage
    - name: provision gateway
      include_tasks: cloud_formation.yml
      with_items:
        - application: gateway
          stack_name: "{{ aws_lambda.gateway.stack_name }}"
          template_parameters: "{{ aws_lambda.gateway.template_parameters }}"
        - application: gateway-stage
          stack_name: "{{ gateway_stage_stack_name }}"
          template_parameters:
            GatewayStack: "{{ aws_lambda.gateway.stack_name }}"
            LambdaStack: "{{ aws_lambda.gateway.template_parameters['LambdaStack'] }}"
            Environment: "{{ env}}"
            LambdaVersionStack: "{{lambda_version_stack_name}}"
    when: aws_lambda.gateway is defined

  - block:
    - name: provision dynamodb stacks
      include_tasks: configure_cloud_formation_stack.yml
      with_items:
            - dynamodb
    - name: provision dynamodb
      include_tasks: cloud_formation.yml
      vars:
        item:
          application: dynamodb
          stack_name: "{{ aws_lambda.dynamodb.stack_name }}"
          template_parameters: "{{ aws_lambda.dynamodb.template_parameters }}"
    when: aws_lambda.dynamodb is defined



