
version: 2

defaults: &defaults
  machine:
    image: circleci/classic:201708-01

  working_directory: ~/aws-lambda

aws_setup: &aws_setup
  run:
    name: configure aws
    command: |
      sudo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY ./aws_credentials.sh

jobs:
  tests:
    <<: *defaults

    steps:
      - checkout
      - *aws_setup
      - run:
          name: Running tests
          command: |
            make test debug=true profile=default


workflows:
  version: 2
  ci:
    jobs:
      - tests
