AWSTemplateFormatVersion: '2010-09-09'
Description: api gateway

Parameters:
  RestApiName:
    Type: String
  Environment:
    Type: String
  LambdaStack:
    Type: String
  CertificateArn:
    Type: String
  DomainName:
    Type: String

Resources:
  RestApi:
    Properties:
      Description: Rest api
      Name: !Ref RestApiName
    Type: AWS::ApiGateway::RestApi

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestApi
      ParentId:
        Fn::GetAtt:
        - RestApi
        - RootResourceId
      PathPart: !Ref RestApiName

  ResourceMethodPOST:
    DependsOn:
    - ApiGatewayResource
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ApiGatewayResource
      RestApiId:
        Ref: RestApi
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: ANY
      MethodResponses:
      - StatusCode: 200
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        IntegrationResponses:
        - StatusCode: 200
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::ImportValue:
                !Sub "${LambdaStack}-lambdaArn"
            - "/invocations"

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RestApi
      StageName: v1
    DependsOn:
    - ResourceMethodPOST

  APILambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::ImportValue:
          !Sub "${LambdaStack}-lambda"
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: RestApi
          - "/*"
    Type: AWS::Lambda::Permission

  APIStage:
    Properties:
      CacheClusterEnabled: false
      DeploymentId:
        Ref: ApiGatewayDeployment
      RestApiId:
        Ref: RestApi
      StageName:
        Ref: Environment
    Type: AWS::ApiGateway::Stage

  CustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref DomainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref CertificateArn

  BaseMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref RestApi


Outputs:
  RootUrl:
    Description: Root URL of the API gateway
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: RestApi
        - ".execute-api."
        - Ref: AWS::Region
        - ".amazonaws.com"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-endpoint"
  
  path:
    Value:
      Fn::Join:
        - ''
        - - ''
          - !Ref Environment
          - "/"
          - !Ref RestApiName

  DomainName:
    Value: !GetAtt
      - CustomDomain
      - RegionalDomainName
